services:
  api:
    build: 
      context: ./src/loaderboo_api/
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./src/loaderboo_api/src:/code/app
      - ./media/:/media
      - ./music/:/music
